listen = ["[::1]:5355", "127.0.0.1:5355"]
upstream = "1.1.1.1"

[[rule]]
domains = ["example.com", "example.org", "ipv4only.arpa"]
strip_a = true
dns64.prefix = "64:ff9b::"

[[rule]]
domains = ["example.net", "httpbin.org"]
upstream = "8.8.8.8"
dns64.prefix = "2001:db8:64::"
dns64.force_synth = true

[[rule]]
domains = "github.com"
upstream = "8.8.8.8"

[[rule]]
domains = "cnki.net"
upstream = ["223.5.5.5", "223.6.6.6"]
